AWSTemplateFormatVersion: 2010-09-09

Parameters:
  EcrRepository:
    Type: String
    Default: account.dkr.ecr.region.amazonaws.com/image
  Tag:
    Type: String
    Default: latest
  BaseImages:
    Type: String
    Default: golang:1.10,alpine:latest
  GitHubRepository:
    Type: String
    Default: https://github.com/cohalz/kaniko-codebuild-example
  ProjectName:
    Type: String
    Default: kaniko-codebuild-example

Resources:
  CodeBuildProjectRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns:
        - Fn::Join:
            - ""
            - - "arn:"
              - Ref: AWS::Partition
              - :iam::aws:policy/AmazonEC2ContainerRegistryPowerUser
  CodeBuildProjectPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Effect: Allow
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CodeBuildProject
              - Fn::Join:
                  - ""
                  - - "arn:"
                    - Ref: AWS::Partition
                    - ":logs:"
                    - Ref: AWS::Region
                    - ":"
                    - Ref: AWS::AccountId
                    - :log-group:/aws/codebuild/
                    - Ref: CodeBuildProject
                    - :*
        Version: "2012-10-17"
      PolicyName: !Sub ${ProjectName}-policy
      Roles:
        - Ref: CodeBuildProjectRole
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Artifacts:
        Type: NO_ARTIFACTS
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_CUSTOM_CACHE
          - LOCAL_DOCKER_LAYER_CACHE
          - LOCAL_SOURCE_CACHE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        Type: LINUX_CONTAINER
        PrivilegedMode: true
        EnvironmentVariables:
          - Name: BASE_IMAGES
            Type: PLAINTEXT
            Value: !Ref BaseImages
          - Name: ECR_REPO
            Type: PLAINTEXT
            Value: !Ref EcrRepository
          - Name: ECR_TAG
            Type: PLAINTEXT
            Value: !Ref Tag
      Name: !Ref ProjectName
      ServiceRole:
        Fn::GetAtt:
          - CodeBuildProjectRole
          - Arn
      Source:
        InsecureSsl: true
        Location: !Ref GitHubRepository
        Type: GITHUB
        GitCloneDepth: 1
        BuildSpec: buildspec.yml
